Directory with ASReml outputs

```{r}
dir.w.RDS.files <- "../results/asreml_kraken_genus_per_age/"
```

Get list of RDS files to collate

```{r}
list.of.RDS.paths <- list.files(dir.w.RDS.files, full.names=T)
length(list.of.RDS.paths)
```

107 features x 5 ages = 535

Initialize outputs

```{r}
list.of.varcomp.dfs <- vector("list", length(list.of.RDS.paths))
age.and.feat.vec <- rep("", length(list.of.RDS.paths))
pval.vec <- rep(0, length(list.of.RDS.paths))
herit.se.vec <- rep(0, length(list.of.RDS.paths))
```

Loop over RDS files

```{r}
for (ii in seq(length(list.of.RDS.paths))) {
  
  this.res <- readRDS(list.of.RDS.paths[[ii]])
  this.age.and.feat <- tools::file_path_sans_ext(basename(list.of.RDS.paths[[ii]]))
  
  list.of.varcomp.dfs[[ii]] <- this.res[["varcomp.df"]] %>% mutate(age.and.feature = this.age.and.feat)
  pval.vec[[ii]] <- this.res[["genetics.LRT.pval"]]
  herit.se.vec[[ii]] <- this.res[["genetic.herit.se"]]
  age.and.feat.vec[[ii]] <- this.age.and.feat
  
}
```

Concatenate

```{r}
varcomp.df <- do.call(rbind, list.of.varcomp.dfs)
pval.df <- data.frame(
  age.and.feature = age.and.feat.vec,
  genetics.LRT.pval = pval.vec)
herit.se.df <- data.frame(
  age.and.feature = age.and.feat.vec,
  herit.se = herit.se.vec)
```

Combine heritability estimate, heritability standard error, and LRT p-values

```{r}
herit.df <- merge(
  varcomp.df %>% 
    dplyr::filter(term == "vm(Mouse, kinship.mat.x2)") %>% 
    dplyr::select(age.and.feature, PVE),
  herit.se.df, by="age.and.feature") %>% 
  merge(pval.df, by="age.and.feature") %>% 
  dplyr::rename(herit = PVE,
                LRT.pval = genetics.LRT.pval)
```

Export `herit.df`

```{r}
write.table(herit.df, sprintf("%s/herit.txt", dir.w.RDS.files),
            sep="\t", quote=F, row.names=F)
```

